# Generated by Django 2.0 on 2019-05-07 16:12

import django.db.models.deletion
from django.db import migrations, models

import parts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('size', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('socket', models.CharField(blank=True, max_length=8, null=True)),
                ('igpu', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ManyToManyField(blank=True, to='parts.Case')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.CPU')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=8)),
                ('vram', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('socket', models.CharField(blank=True, max_length=8)),
                ('chipset', models.CharField(blank=True, max_length=16)),
                ('size', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('wattage', models.IntegerField(blank=True)),
                ('certification', models.CharField(blank=True, choices=[('-', '-'), ('80 PLUS', '80 PLUS'),
                                                                        ('80 PLUS Bronze', '80 PLUS Bronze'),
                                                                        ('80 PLUS Silver', '80 PLUS Silver'),
                                                                        ('80 PLUS Gold', '80 PLUS Gold'),
                                                                        ('80 PLUS Platinum', '80 PLUS Platinum'),
                                                                        ('80 PLUS Titanium', '80 PLUS Titanium')],
                                                   default='-', max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, validators=[parts.models.validate_skroutz_url])),
                ('name', models.CharField(blank=True, max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('size', models.IntegerField(blank=True)),
                ('speed', models.IntegerField(blank=True)),
                ('number_of_modules', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parts.GPU'),
        ),
        migrations.AddField(
            model_name='entity',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parts.Motherboard'),
        ),
        migrations.AddField(
            model_name='entity',
            name='psu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.PSU'),
        ),
        migrations.AddField(
            model_name='entity',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.RAM'),
        ),
        migrations.AddField(
            model_name='entity',
            name='rest_items',
            field=models.ManyToManyField(blank=True, to='parts.Part'),
        ),
    ]
