# Generated by Django 2.0 on 2019-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cores',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
