# Generated by Django 2.0 on 2019-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parts', '0002_auto_20190507_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='igpu',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vram',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='size',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='wattage',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='number_of_modules',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='size',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='speed',
        ),
    ]
